parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    _instanceof:
        AppBundle\Model\ModelManagerAwareInterface:
            tags:
                - { name: model.manager }
        Doctrine\Common\EventSubscriber:
            tags:
                - { name: doctrine.event_subscriber }

    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Request\ParamConverter\UuidParamConverter:
        decorates: sensio_framework_extra.converter.doctrine.orm
        autowire: true
        public: false
